### ISSUE TITLE
[Bug] Incorrect count of Calamity Bosses and support for add-ons

### ISSUE THREAD

**Issue by vavavr00m** [JavidPack/BossChecklist#129]
Calamity mod has 27 bosses and 12 minibosses = 39 according to the description page but Boss Checklist only shows 26 bosses + 5 minibosses + 4 events = 35

The following Calamity addons are also installed but the mod cannot detect and list down the bosses. Even if they have similar names, I feel like they should be displayed along with the difference in stats. 
[Calamity: Community Remix](https://steamcommunity.com/sharedfiles/filedetails/?id=2956324268) - 1 extra boss (per the workshop page)
[Calamity Mod Infernum Mode](https://steamcommunity.com/sharedfiles/filedetails/?id=3015412343) - harder
[Calamity Infernum Master and Legendary Modes Patch](https://steamcommunity.com/sharedfiles/filedetails/?id=2906406399) - harder

**Comment by SheepishShepherd** [comment]
The bosses is actually 26 according to their [wiki](https://calamitymod.wiki.gg/wiki/Bosses) page, so that might be a typo on their description. As for the mini-bosses, it has been confirmed by a Calamity developer and I that only 5/12 mini-bosses are registered. It is unknown when the other 7 mini-bosses will be registered, but it must be done by Calamity. BossChecklist does not manually add any content from other mods.

As for the other mods, they are made by other developers. You can contact them (maybe they have a discord server, I'm not sure) to see if they can register their bosses. You can redirect them to our [GitHub's wiki](https://github.com/JavidPack/BossChecklist/wiki/%5B1.4.4%5D-Boss-Log-Entry-Mod-Call) page as it explains the process of registering in detail.
