### ISSUE TITLE
Need chinese translation?

### ISSUE THREAD

**Issue by Crapsky233** [JavidPack/BossChecklist#16]
I am chinese. And I would like to make a chinese translation of this Mod

**Comment by JavidPack** [comment]
That would be great. To do this, simply make a zh-Hans.lang file in the Localization folder with the exact contents of this file, but with the chinese to the right of the `=`. https://github.com/JavidPack/BossChecklist/blob/master/Localization/en-US.lang

If you are familiar with using Github, you can make a pull request with that file, otherwise I can handle it if you just post it to this issue thread.

**Comment by Crapsky233** [comment]
Alright. But what about the other texts? Such as spawn infos & boss records

**Comment by Crapsky233** [comment]
@JavidPack 
Is there any problem with the BossChecklist.cs that I just pulled? If yes, please tell me the right way. I am not familiar enough about it.

**Comment by JavidPack** [comment]
@Crapsky233 I've just updated your code and moved stuff around. I can release this update right away, or you can translate the missing event and miniboss spawn conditions: https://github.com/JavidPack/BossChecklist/blob/master/Localization/zh-Hans.lang

**Comment by Crapsky233** [comment]
@JavidPack Alright. I'll translate them later.

**Comment by Crapsky233** [comment]
@JavidPack I pulled them just now.

**Comment by JavidPack** [comment]
Amazing, thanks a bunch. 

I do know that currently the lack of spaces in the Chinese text prevents the game from properly wrapping the text sometimes, I'll try to figure out a good approach.
